title: EVTA-Austria

description: > # this means to ignore newlines until "baseurl:"
 Die EVTA-Austria versteht sich als Interessensvertretung von Gesangspädagogen, 
 Stimmbildnern und fachverwandten Berufen.

# the subpath of your site, e.g. /blog
baseurl: 

# the base hostname & protocol for your site
url: https://evta.at
author: Michael Gerzabek
email: michael.gerzabek@gmail.com

# Wir wollen alle Formate auf Deutsch haben…    
locale: "de-AT"

skin: default

# Build settings
highlighter: rouge
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## Kramdown settings
kramdown:  
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: /articles/:short_year/:title
timezone: Europe/Vienna

sass:
  style: compressed
  
## HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

exclude:
- _config
- README.md
- Gemfile
- Gemfile.lock

plugins:
  - jekyll-seo-tag

css:
  version: 0.9.0
  
## Google Analytics    
#
# google_analytics: 

## Facebook
#    
#facebook:
#  app_id: 
#  publisher: 
#  admins: 

## Disqus Comments
#
#disqus:
#    shortname: 

## Google Recaptcha SPAM defender
#
# recaptcha:
#   site-key: 
#   private-key: 
